### ISSUE TITLE
False fields removed from filter

### ISSUE THREAD

**Issue by codesxt** [lykmapipo/express-mquery#6]
Hi. I'm passing a parameter as false in filter but it's being removed from the filter. It only appears when it's set as true.

The parameter is called 'accepted'. I'm printing the values for req.query and req.mquery for each case:
```
For false:
req.query = { accepted: 'false' }
req.mquery =  undefined
```

```
For true:
req.query = { accepted: 'true' }
req.mquery = { accepted: true }
```

**Comment by codesxt** [comment]
I just checked your source code and found out that false values are being removed in line 66 of parser.js because of the condition `val => !val` which excludes false and undefined values. I believe it should only exclude undefined values, so I'll open a PR for that little change.

**Comment by codesxt** [comment]
Added PR: #7

**Comment by lykmapipo** [comment]
@codesxt On it
